workflows:
  android-workflow:
    name: Compilar APK Android
    instance_type: mac_mini_m1
    max_build_duration: 30
    scripts:
      - name: Regenerar carpeta Android
        script: |
          rm -rf android
          flutter create --platforms=android --org com.denniscastillo .
      - name: Obtener paquetes
        script: flutter pub get
      - name: Generar APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
